version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    depends_on:
      - postgres
    ports:
      - "9000:3000"  # Map container's port 3000 to host's port 9000

volumes:
  postgres_data:
