version: '3'

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_container
    ports:
      - "9000:3000"  # Map container's port 3000 to host's port 9000
